const RegionalIndicators = {
    A: '🇦',
    B: '🇧',
    C: '🇨',
    D: '🇩',
    E: '🇪',
    F: '🇫',
    G: '🇬',
    H: '🇭',
    I: '🇮',
    J: '🇯',
    K: '🇰',
    L: '🇱',
    M: '🇲',
    N: '🇳',
    O: '🇴',
    P: '🇵',
    Q: '🇶',
    R: '🇷',
    S: '🇸',
    T: '🇹',
    U: '🇺',
    V: '🇻',
    W: '🇼',
    X: '🇽',
    Y: '🇾',
    Z: '🇿'
} as Record<string,string>;

export const CountryCodes = {
    'AU': 'Australia',
    'BR': 'Brazil',
    'CN': 'China',
    'CO': 'Colombia',
    'CW': 'Curaçao',
    'DE': 'Germany',
    'EC': 'Ecuador',
    'FI': 'Finland',
    'FM': 'Micronesia',
    'FR': 'France',
    'GU': 'Guam',
    'GW': 'Guinea-Bissau',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IM': 'Isle of Man',
    'IN': 'India',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JP': 'Japan',
    'KN': 'Saint Kitts and Nevis',
    'MF': 'Saint Martin',
    'MK': 'North Macedonia',
    'MO': 'Macau',
    'MQ': 'Martinique',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'PR': 'Puerto Rico',
    'PS': 'Palestine',
    'RE': 'Réunion',
    'SE': 'Sweden',
    'TC': 'Turks and Caicos Islands',
    'TL': 'East Timor',
    'TT': 'Trinidad and Tobago',
    'UG': 'Uganda',
    'US': 'United States',
    'VC': 'Saint Vincent and the Grenadines',
    'VE': 'Venezuela',
    'VI': 'U.S. Virgin Islands',
    'WF': 'Wallis and Futuna',
    'WI': 'Worldwide',
    'YT': 'Mayotte',

} as Record<string,string>;

export const ReverseCountryCodes = Object.fromEntries(Object.entries(CountryCodes).map(([a,b]) => [b,a]));

export function getCountryFlag(country: string) {
    if (country == 'UK') return '🇬🇧';
    if (country == 'WI') return '🌐';
    return country.split('').map(a => RegionalIndicators[a.toUpperCase()] || a).join('');
}